# Example: Creating 1Password Connect Secrets
#
# These secrets must be created BEFORE deploying the onepassword-connect Application.
# The secrets are referenced by the Helm chart but not created by it.
#
# Prerequisites:
# 1. Log into 1Password at https://start.1password.com
# 2. Go to Settings → Developer → Infrastructure Secrets Management
# 3. Create a new Connect Server
# 4. Download the 1password-credentials.json file
# 5. Generate an access token (save it, you'll only see it once)
#
# ==============================================================================
# CRITICAL: Credentials Secret Encoding
# ==============================================================================
# The 1Password Connect server expects OP_SESSION to contain base64-encoded JSON.
# When using Kubernetes secrets with `data:`, values are automatically base64-encoded,
# which causes double-encoding. Use `stringData:` with pre-encoded JSON instead.

---
# 1. Credentials Secret (MUST use stringData with base64-encoded JSON)
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-credentials
  namespace: onepassword
type: Opaque
stringData:
  # IMPORTANT: This must be base64-encoded JSON, NOT raw JSON
  # Generate with: cat 1password-credentials.json | base64
  1password-credentials.json: |-
    <BASE64_ENCODED_JSON_HERE>

# Example of how to create it from your credentials file:
#
#   cat 1password-credentials.json | base64 > credentials-encoded.txt
#
#   kubectl create namespace onepassword
#
#   cat <<EOF | kubectl apply -f -
#   apiVersion: v1
#   kind: Secret
#   metadata:
#     name: onepassword-credentials
#     namespace: onepassword
#   type: Opaque
#   stringData:
#     1password-credentials.json: |-
#       $(cat credentials-encoded.txt)
#   EOF

---
# 2. Token Secret (raw token, NOT base64-encoded)
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: onepassword
type: Opaque
stringData:
  token: <YOUR_1PASSWORD_TOKEN_HERE>

# Example of how to create it:
#
#   kubectl create secret generic onepassword-token \
#     --from-literal=token="YOUR_TOKEN_HERE" \
#     --namespace onepassword

# ==============================================================================
# Verification
# ==============================================================================
# After creating secrets and deploying the Application, verify:
#
#   # Check pods are running
#   kubectl get pods -n onepassword
#
#   # Check Connect sync logs (should see "credentials bootstrap complete")
#   kubectl logs -n onepassword deployment/onepassword-connect -c connect-sync
#
#   # Should NOT see "illegal base64 data" errors
#
# ==============================================================================
# Troubleshooting
# ==============================================================================
# If you see "illegal base64 data at input byte 0" error:
#   - The credentials secret was created incorrectly
#   - You used `data:` instead of `stringData:`
#   - OR you didn't base64-encode the JSON before putting it in stringData
#   - Fix: Delete and recreate the secret following the example above
