apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: monitoring  # Must be in same namespace as Grafana
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-stack:3100
        jsonData:
          maxLines: 1000
          derivedFields:
            # Link log lines to traces (if using Tempo in the future)
            - datasourceUid: tempo
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
        editable: true
        isDefault: false
