apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: litellm-master-key
  namespace: litellm
spec:
  itemPath: "vaults/kubernetes/items/litellm-master-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: litellm-postgresql
  namespace: litellm
spec:
  itemPath: "vaults/kubernetes/items/litellm-postgresql"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: litellm-vllm-upstreams
  namespace: litellm
spec:
  itemPath: "vaults/kubernetes/items/litellm-vllm-upstreams"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: langfuse-project-api-keys
  namespace: litellm
spec:
  itemPath: "vaults/kubernetes/items/langfuse-project-api-keys"
