apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: connect
      app.kubernetes.io/instance: onepassword-connect
  endpoints:
    - port: connect-api
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
