apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: langfuse-core-secrets
  namespace: langfuse
spec:
  itemPath: "vaults/kubernetes/items/langfuse-core-secrets"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: langfuse-postgresql
  namespace: langfuse
spec:
  itemPath: "vaults/kubernetes/items/langfuse-postgresql"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: langfuse-redis
  namespace: langfuse
spec:
  itemPath: "vaults/kubernetes/items/langfuse-redis"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: langfuse-clickhouse
  namespace: langfuse
spec:
  itemPath: "vaults/kubernetes/items/langfuse-clickhouse"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: langfuse-minio
  namespace: langfuse
spec:
  itemPath: "vaults/kubernetes/items/langfuse-minio"
