apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email for expiration notifications
    email: jimmychads@proton.me

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: cilium
