apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: paperclip-app-secrets
  namespace: paperclip
spec:
  itemPath: "vaults/kubernetes/items/paperclip-app-secrets"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: paperclip-postgresql
  namespace: paperclip
spec:
  itemPath: "vaults/kubernetes/items/paperclip-postgresql"
