apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcpproxy-data
  namespace: mcpproxy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
