apiVersion: v1
kind: Service
metadata:
  name: unla
  namespace: unla
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mcp.internal
    io.cilium/lb-ipam-ips: "192.168.0.206"
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  selector:
    app: unla
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: mcp
      port: 5235
      targetPort: 5235
