apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: volume-backup-daily
  namespace: longhorn-system
spec:
  cron: "30 6 * * *"
  task: backup
  groups:
    - default
  retain: 14
  concurrency: 2
  labels:
    backup-tier: volume
  parameters:
    full-backup-interval: "7"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: system-backup-daily
  namespace: longhorn-system
spec:
  cron: "45 6 * * *"
  task: system-backup
  retain: 7
  concurrency: 1
  labels:
    backup-tier: system
  parameters:
    volume-backup-policy: if-not-present
